export const data = [
  {
    storeid: 1,
    storeNumber: '001',
    storeName: 'IGA #001',
    termCount: 7,
    version: '1.1.0',
    group: 1,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 2,
    storeNumber: '002',
    storeName: 'IGA #002',
    termCount: 4,
    version: '1.1.0',
    group: 1,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 3,
    storeNumber: '003',
    storeName: 'IGA #003',
    termCount: 3,
    version: '1.1.1',
    group: 1,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 4,
    storeNumber: '800',
    storeName: 'JR Foods #800',
    termCount: 2,
    version: '1.1.1',
    group: 2,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 5,
    storeNumber: '801',
    storeName: 'JR Foods #801',
    termCount: 3,
    version: '1.1.0',
    group: 2,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 6,
    storeNumber: '700',
    storeName: 'Crossroadds #700',
    termCount: 5,
    version: '1.1.0',
    group: 3,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 7,
    storeNumber: '701',
    storeName: 'Crossroadds #701',
    termCount: 4,
    version: '1.1.1',
    group: 3,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 8,
    storeNumber: '702',
    storeName: 'Crossroadds #702',
    termCount: 4,
    version: '1.1.1',
    group: 3,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 9,
    storeNumber: '703',
    storeName: 'Crossroadds #703',
    termCount: 4,
    version: '1.1.1',
    group: 3,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
  {
    storeid: 10,
    storeNumber: '705',
    storeName: 'Crossroadds #705',
    termCount: 4,
    version: '1.1.1',
    group: 3,
    image: {
      url: 'https://www.datacashreg.com/DMS/_images/pinpadlogos/l5300.png',
      name: 'l5300',
      height: '20',
      width: '30',
    },
  },
];

export const data2 = [
  {
    id: 1,
    name: 'Whataburgers',
    state: 'ky',
    employees: 50,
  },
  {
    id: 2,
    name: 'McDonalds',
    state: 'tn',
    employees: 25,
  },
  {
    id: 3,
    name: 'Dennys',
    state: 'tn',
    employees: 125,
  },
  {
    id: 4,
    name: 'Wendys',
    state: 'ky',
    employees: 15,
  },
  {
    id: 5,
    name: 'Taco Bell',
    state: 'ky',
    employees: 42,
  },
];
